version: "3.8"

services:
  # 1. DATABASE: PostgreSQL
  db:
    image: postgres:15
    container_name: khmer_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # 2. BACKEND: FastAPI + ML Model
  backend:
    build: ./backend
    container_name: khmer_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  # 3. FRONTEND: React (Nginx)
  frontend:
    build: ./frontend
    container_name: khmer_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" # Access your website at http://localhost:3000
    env_file:
      - ./frontend/.env # Specifically uses the frontend environment variables

volumes:
  postgres_data:
